config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'register', to: 'devise/registrations#create'
  end

  root 'home#index'
  get '/dashboard' => 'dashboard#index'
  get '/dashboard/search' => 'dashboard#search', as: 'dashboard/search'
  get '/favorites/saverecipe' => 'favorites#save_recipe', as: 'favorites/save_recipe'

  get '/favorites' => 'favorites#index'
  post '/favorites' => 'favorites#create', as: 'create_favorite'
  get '/favorites/new' => 'favorites#new', as: 'new_favorite'
  delete '/favorites/:id' => 'favorites#destroy', as: 'delete_favorite'

  get '/dashboard/random_recipe', to: 'random_recipe#random', as: 'random_recipe'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :query_options

  def index
  end

  def search
    @query = params[:query]
    @diet = params[:diet]
    @health = params[:health]
    @cuisine = params[:cuisine]
    @dish = params[:dish]
    @exclude = params[:exclude]
    get_api
    
  end

  def get_api
    return unless @query

    @search_response = SearchService.search(@query, @diet, @health, @cuisine, @dish, @exclude)
    @paginatable_array = Kaminari.paginate_array(@search_response,
                                                 total_count: @search_response.count).page(params[:page]).per(7)
  end

  private

  def query_options
    @diet_array = ['', 'balanced', 'high-fiber', 'high-protein', 'low-carb', 'low-fat', 'low-sodium']
    @health_array = ['', 'alcohol-cocktail', 'alcohol-free', 'celery-free', 'crustacean-free', 'dairy-free',
                     'DASH', 'egg-free', 'fish-free', 'foodmap-free', 'gluten-free', 'immuno-supportive', 'keto-friendly',
                     'kidney-friendly', 'kosher', 'low-fat-abs', 'low-potassium', 'low-sugar', 'lupine-free', 'meditteranean',
                     'mollusk-free', 'mustard-free', 'no-oil-added', 'paleo', 'peanut-free', 'pescatarian', 'pork-free',
                     'red-meat-free', 'sesame-free', 'shellfish-free', 'soy-free', 'sugar-conscious', 'sulfite-free',
                     'tree-nut-free', 'vegan', 'vegetarian']
    @cuisine_array = ['', 'american', 'asian', 'british', 'caribbean', 'central europe', 'chinese',
                      'eastern europe', 'french', 'indian', 'italian', 'japanese', 'kosher', 'mediterranean', 'mexican',
                      'middle eastern', 'nordic', 'south american', 'south east asian']
    @dish_array = ['', 'biscuits and cookies', 'bread', 'cereals', 'condiments and sauces', 'desserts', 'drinks',
                   'main course', 'pancake', 'preps', 'preserve', 'salad', 'sandwiches', 'side dish', 'soup', 'starter', 'sweets']
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_queries.html.erb
<%= form_tag dashboard_search_path, method: :get do %>

        <%= text_field_tag :query, @query %>
        <%= submit_tag "Search" %></br>

        <p id="filters_span">Filters <span>(optional)</span></p>

        <span id="exclude_span">Exclude ingredient:</span>
        <%= text_field_tag :exclude, @exclude %></br>
        <span>Diet:</span>
        <%= select_tag(:diet, options_for_select(@diet_array.map { |d| [d, d] },  @diet))%>
        <span>Health:</span>
        <%= select_tag(:health, options_for_select(@health_array.map { |h| [h, h] }, @health)) %>
        <span>Cuisine Type:</span>
        <%= select_tag(:cuisine, options_for_select(@cuisine_array.map { |c| [c, c] }, @cuisine)) %>
        <span>Dish Type:</span>
        <%= select_tag(:dish, options_for_select(@dish_array.map { |s| [s, s] }, @dish)) %>

<% end %>

app/views/dashboard/index.html.erb
<div id="dashboard_container">
    <h1>Dashboard</h1>

    <%= render "queries" %>
</div>

app/views/dashboard/search.html.erb
<script>


    function favorite(el) {
        event.preventDefault();
        el.style.display = "none"
        el.nextElementSibling.style.display = "block"
        const recipeName = el.getAttribute('data-recipe-name')
        const recipeUrl = el.getAttribute('data-recipe-url')
        const recipeIngredients= el.getAttribute('data-recipe-ingredients')
        const recipeImage= el.getAttribute('data-recipe-image')

        const get_url = new XMLHttpRequest();
        get_url.open('GET', '<%= favorites_save_recipe_path %>' + '?variable_name=' + recipeName + '&variable_url=' + recipeUrl + '&variable_ing=' + recipeIngredients + '&variable_image=' + recipeImage )
        get_url.onload = function() {

            if (get_url.status === 200) {
                console.log('get url success', get_url.responseText)
            } else {
                console.log('Request failed. Returned status of ' + get_url.status);
            }
        };
        get_url.send();
    }    

   function unfavorite(el) {
        el.style.display = "none"
        el.previousElementSibling.style.display = "block"
        console.log("unfavorite", el)
    }
</script>

<div id="dashboard_search_container">
    <h1>Dashboard</h1>
    <% link_to(image_tag("heart.png"), root_path) %>

    <%= render "queries" %>
    <div class="recipe_response">

        <% @paginatable_array.map do |recipe| %>
            <%= link_to recipe['recipe']['url'] do %>
                <div class="recipe_block">
                
                    <%= link_to recipe['recipe']['url'] do %>
                        <div class="recipe_link_block">
                            <h4><%= recipe['recipe']['label'] %></h4>
                            <img src="<%= recipe['recipe']['image'] %>"/> </br>
                        </div>
                    <% end %> 

                    <% @recipe_text = recipe['recipe']['ingredients'] %>
                            <% i = 0 %>
                            <% @ingredients = '' %>
                                <% while i < @recipe_text.count do %>
                                    <% if i == 0 %>
                                        <% @ingredients.concat("#{@recipe_text[i]['food'].capitalize} ") %>
                                    <% elsif i == @recipe_text.count - 1 %>
                                        <% @ingredients.concat("and #{@recipe_text[i]['food'].downcase}.") %>
                                    <% else %>
                                        <% @ingredients.concat("#{@recipe_text[i]['food'].downcase}, ") %>
                                    <% end %>
                                    <% i += 1 %>
                                <% end %> </br>
                            
                            <h5 class="ingredients_h5"> Ingredients: <span> <%= @ingredients %> </span> </h5>
                            
                            <%= button_tag(id: "empty_heart", onclick: "favorite(this)", data: { recipe_name: recipe['recipe']['label'], recipe_url: recipe['recipe']['url'], recipe_ingredients: @ingredients, recipe_image: recipe['recipe']['image'] }) do %>
                                <%= image_tag("heart.png") %>
                            <% end %>
                            <%= button_tag(id: "filled_heart", onclick: "unfavorite(this)") do %>
                                <%= image_tag("filled_heart.png") %>
                            <% end %>

                    
                </div>
                
            <% end %> 

        <% end %> 
    </div>

    <%= paginate @paginatable_array %>


</div>