config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'register', to: 'devise/registrations#create'
  end

  root 'home#index'
  get '/dashboard' => 'dashboard#index'
  get '/dashboard/search' => 'dashboard#search', as: 'dashboard/search'
  get '/favorites/saverecipe' => 'favorites#save_recipe', as: 'favorites/save_recipe'

  get '/favorites' => 'favorites#index'
  post '/favorites' => 'favorites#create', as: 'create_favorite'
  get '/favorites/new' => 'favorites#new', as: 'new_favorite'
  delete '/favorites/:id' => 'favorites#destroy', as: 'delete_favorite'

  get '/dashboard/random_recipe', to: 'random_recipe#random', as: 'random_recipe'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    validates :name, uniqueness: true

    belongs_to :user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # after_action :set_favorite, only: %i[ save_recipe ]
  before_action :find_user
  after_action :create, only: %i[ save_recipe ]
  before_action :set_favorite, only: %i[ destroy ]

  def index
    @user = current_user
    @favorites = @user.favorites
  end

  def new 
    @favorite = Favorite.new
  end

  def save_recipe 
    @recipe_name = params[:variable_name]
    @recipe_url = params[:variable_url]
    @recipe_ing = params[:variable_ing]
    @recipe_image = params[:variable_image]

    render json: {name: @recipe_name, url: @recipe_url, ingredients: @recipe_ing, image: @recipe_image}

  end

  def destroy
    @favorite.destroy
  end

  private
  def create 
    @user = current_user
    @favorite = current_user.favorites.new(name: @recipe_name, url: @recipe_url, image: @recipe_image, ingredients: @recipe_ing)

    if @favorite.save
      # flash[:notice] = 'Favorite was successfully created.'
      redirect_to favorites_path
    else
      # flash[:alert] = "You've already saved this recipe."
      flash[:error] = "Something went wrong."
      redirect_to dashboard_search_path and return
    end

  end

  def find_user
    @user = current_user
  end
  
  def set_favorite
    @favorite = @user.favorites.find(params[:id])
  end

  def favorite_params
    params.require(:favorite).permit(:name, :url, :image, :ingredients)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/index.html.erb
<h1 id="h1_favorites">Saved Recipes of 
<% @user = current_user.first_name.capitalize %> 
<%= @user %>
</h1>
<div id="favorites_recipe_container">
    <% @favorites.sort.each do |favorite| %>
        <div class="favorites_recipe_block">
            <div class="favorites_recipe_link">
                <%= link_to favorite.url do %>
                    <h3><%= favorite.name.upcase %></h3>
                    <%= favorite.ingredients %>
                <% end %>
            </div>
            <div id="heart_favorites_container">
                <%= link_to delete_favorite_path(favorite.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{favorite.name}?" }, :id => "delete_favorite_link filled_heart" do %>
                    <%= image_tag("filled_heart.png") %>
                <% end %>
            </div>
            </div>
    <% end %>
</div>