config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'register', to: 'devise/registrations#create'
  end

  root 'home#index'
  get '/dashboard' => 'dashboard#index'
  get '/dashboard/search' => 'dashboard#search', as: 'dashboard/search'
  get '/favorites/saverecipe' => 'favorites#save_recipe', as: 'favorites/save_recipe'

  get '/favorites' => 'favorites#index'
  post '/favorites' => 'favorites#create', as: 'create_favorite'
  get '/favorites/new' => 'favorites#new', as: 'new_favorite'
  delete '/favorites/:id' => 'favorites#destroy', as: 'delete_favorite'

  get '/dashboard/random_recipe', to: 'random_recipe#random', as: 'random_recipe'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeGenerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Climate+Crisis&family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/dc17da3622.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
    </head>
  
  <header class="nav-div">
    <div class="img-div">
      <%= link_to(image_tag("wyup-icon.png"), root_path) %>
      <span id="wyup-span" >WYUP</span>
    </div>

      <% if current_user %>
        <div id="page-links">
          <%= link_to "Home", random_recipe_path %>
          <span>|</span>
          <%= link_to "Recipe Search", dashboard_path %>
          <span>|</span>
          <%= link_to "Favorites", favorites_path %>
        </div>

      <% end %>

    <div class="nav-btns" >
      <% if current_user %>
        <div class="nav_current_buttons">
          <div class="current_user_nav">
            <span> <%= current_user.first_name.capitalize %> </span>
          </div>
            <span class="sign-out-btn"><%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %></span>
        </div>
         <% else %>
         <div class="no_session_buttons">
          <span class="sign-in-btn"> <%= link_to "Sign in",   new_user_session_path %> </span>
          <span class="register-btn"><%= link_to "Register",  new_user_registration_path %></span>
        </div>

      <% end %>
    </div>
  </header>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>